

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        type: com.mchange.v2.c3p0.ComboPooledDataSource
#        url: jdbc:mysql://124.71.162.78:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        url: jdbc:mysql://127.0.0.1:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
server:
    port: 8848

mybatis:
    mapper-locations: classpath*:/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
