

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: nzh
        password: 123456
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        url: jdbc:mysql://193.112.195.243:3306/crmmangement?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
server:
    port: 8848

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:/mapper/*.xml