spring:
<<<<<<< HEAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #         password: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://124.71.162.78:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  #          url: jdbc:mysql://127.0.0.1:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 124.71.162.78
  #       host: 127.0.0.1
=======
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
#        password: root
        password: 123456
#        type: com.mchange.v2.c3p0.ComboPooledDataSource
        url: jdbc:mysql://124.71.162.78:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#        url: jdbc:mysql://127.0.0.1:3306/db_forum?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false


    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
        host: 124.71.162.78
#        host: 127.0.0.1
>>>>>>> 782d0409b758da0e067f5a2bffcda29a435a327c
server:
  port: 8848

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

c3p0:
  minPoolSize: 2
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
  checkoutTimeout: 6000